### ISSUE TITLE
Wrong constant

### ISSUE THREAD

**Issue by Felis-Sapiens** [jclehner/upc-twg8x0#1]
Instead of

```
//v0 = mult_mfhi(s0, 0xd6bf963f) >> 23;
v0 = s0 / 10000000;
```

it must be:

```
v0 = s0 / 9999999;
```

I would like to take a look at the binary. Could you provide me with the firmware dump?

**Comment by jclehner** [comment]
Fixed in the latest commit. Also, check your email.
